### ISSUE TITLE
codecserver-mbelib-module

### ISSUE THREAD

**Issue by fventuri** [knatterfunker/codecserver-softmbe#4]
(not really an issue)
I just found out about your module for OpenWebRX codecserver.
I had the same problem so I too ended up writing something very similar to yours: https://github.com/fventuri/codecserver-mbelib-module

Franco

**Comment by knatterfunker** [comment]
This is very cool, congrats! We added a link to your project in "related works". We know of users who tried to mention our project on the official openwebrx discussion board and these comments have been censored. Therefore it is not surprising that different groups have started to work on this in parallel without knowing of each other.

I'm closing this issue since I believe this has been sorted. Keep up the nice work!
